SUTFProjeYonetimi/Models/Proje.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SUTFProjeYonetimi.Models
{
	public class Proje
	{
		[Key, DisplayName("Proje No.")]
		public int ID { get; set; }

		[DisplayName("Fakülte")]
		public int FakulteID { get; set; }

		[DisplayName("Bölüm")]
		public int BolumID { get; set; }

		[DisplayName("Dönemi")]
		public int DonemID { get; set; }

		[DisplayName("Öğrenci")]
		public int OgrenciID { get; set; }

		[DisplayName("Danışman")]
		public int DanismanID { get; set; }

		public string ProjeNo { get; set; }

		public int ProjeTipi { get; set; }

		[Required, MaxLength(255), DisplayName("Proje Adı")]
		public string ProjeAdi { get; set; }

		[Required, MaxLength(255), DisplayName("Proje Açıklaması")]
		public string ProjeAciklamasi { get; set; }

		[DisplayName("Proje Konusu ve Amacı")]
		public string ProjeKonusuAmaci { get; set; }

		[DisplayName("Maliyet Araştırması")]
		public string MaliyetArastirmasi { get; set; }

		[DisplayName("Çevresel Etkileri")]
		public string CevreselEtkileri { get; set; }

		[DisplayName("Etik Sakıncaları")]
		public string EtikSakincalari { get; set; }

		[DisplayName("Yaralanılan Kaynaklar")]
		public string YararlanilanKaynaklar { get; set; }

		public DateTime Tarih { get; set; }

		public int Durum { get; set; }

		[DisplayName("Ek Dosya")]
		public string EkDosya { get; set; }

		[DisplayName("Başlangıç Tarihi")]
		public DateTime BaslangicTarihi { get; set; }

		[DisplayName("Bitiş Tarihi")]
		public DateTime BitisTarihi { get; set; }

		public string Rapor { get; set; }

		[MaxLength(255), DisplayName("Ek Alan-1")]
		public string EkAlan1 { get; set; }

		[MaxLength(255), DisplayName("Ek Alan-2")]
		public string EkAlan2 { get; set; }

		public bool Etkin { get; set; }

		public bool Silindi { get; set; }
	}
}

SUTFProjeYonetimi/Controllers/ProjeController.cs
using SUTFProjeYonetimi.Filters;
using SUTFProjeYonetimi.Models;
using SUTFProjeYonetimi.Models.EkModel;
using SUTFProjeYonetimi.Models.Enum;
using SUTFProjeYonetimi.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using static SUTFProjeYonetimi.App_Start.Tanimlamalar;

namespace SUTFProjeYonetimi.Controllers
{
	[HataFilter]
	[AnlikOturumFilter]
	[DanismanFilter]
	public class ProjeController : Controller
	{
		#region ProjeIslemleri

		public ActionResult Liste()
		{
			List<VProje> projeler;
			switch (AnlikOturum.Kullanici.Yetki)
			{
				case (int)Yetkilendirme.SystemAdmin: projeler = vprojeIslemleri.VeriGetir(); break;
				case (int)Yetkilendirme.Dekan:
					projeler = vprojeIslemleri.VeriGetir("FakulteID = " + AnlikOturum.Kullanici.Akademisyen.FakulteID); break;
				case (int)Yetkilendirme.BolumBaskani:
					projeler = vprojeIslemleri.VeriGetir("FakulteID = " + AnlikOturum.Kullanici.Akademisyen.FakulteID + " And BolumID = " + AnlikOturum.Kullanici.Akademisyen.BolumID); break;
				case (int)Yetkilendirme.Danisman:
					projeler = vprojeIslemleri.VeriGetir("FakulteID = " + AnlikOturum.Kullanici.Akademisyen.FakulteID + " And BolumID = " + AnlikOturum.Kullanici.Akademisyen.BolumID + " And  DanismanID = " + AnlikOturum.Kullanici.Akademisyen.ID); break;
				case (int)Yetkilendirme.Ogrenci:
					return RedirectToAction("Panel", "Anasayfa");
				default:
					projeler = new List<VProje>(); break;
			}
			return View(projeler);
		}

		public ActionResult Detay(int? id)
		{
			if (id == null)
				return RedirectToAction(nameof(Liste));

			Proje proje;
			switch (AnlikOturum.Kullanici.Yetki)
			{
				case (int)Yetkilendirme.SystemAdmin: proje = projeIslemleri.Bul("ID = " + id); break;
				case (int)Yetkilendirme.Dekan:
					proje = projeIslemleri.Bul("ID = " + id + " And FakulteID = " + AnlikOturum.Kullanici.Akademisyen.FakulteID + " And Silindi = 0"); break;
				case (int)Yetkilendirme.BolumBaskani:
					proje = projeIslemleri.Bul("ID = " + id + " And FakulteID = " + AnlikOturum.Kullanici.Akademisyen.FakulteID + " And BolumID = " + AnlikOturum.Kullanici.Akademisyen.BolumID + " And Silindi = 0"); break;
				case (int)Yetkilendirme.Danisman:
					proje = projeIslemleri.Bul("ID = " + id + " And FakulteID = " + AnlikOturum.Kullanici.Akademisyen.FakulteID + " And BolumID = " + AnlikOturum.Kullanici.Akademisyen.BolumID + " And  DanismanID = " + AnlikOturum.Kullanici.Akademisyen.ID + " And Silindi = 0"); break;
				case (int)Yetkilendirme.Ogrenci:
					return RedirectToAction("Anasayfa", "Panel");
				default:
					proje = null; break;
			}
			if (proje == null)
				return HttpNotFound();

			return View(proje);
		}

		public ActionResult Ekle()
		{
			ViewData["ProjeTipi"] = SLOlusturma.ProjeTipiListele(AnlikOturum.Kullanici.Akademisyen.FakulteID);
			ViewData["ProjeDurumu"] = SLOlusturma.ProjeDurumuListele();
			ViewData["Fakulte"] = SLOlusturma.FakulteListele();
			ViewData["Bolum"] = SLOlusturma.BolumListele();
			ViewData["Danisman"] = SLOlusturma.AkademisyenListele(AnlikOturum.Kullanici.Akademisyen.FakulteID, AnlikOturum.Kullanici.Akademisyen.BolumID);
			ViewData["Ogrenci"] = SLOlusturma.OgrenciListele(AnlikOturum.Kullanici.Akademisyen.FakulteID, AnlikOturum.Kullanici.Akademisyen.BolumID);

			return View("EkleDuzenle");
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Ekle(Proje proje)
		{
			if (ModelState.IsValid)
			{
				VBolum vBolum = vbolumIslemleri.Bul("FakulteID = " + proje.FakulteID + " And BolumID = " + proje.BolumID);
				int oncekiProjeID = projeIslemleri.MaxDeger("ID");
				oncekiProjeID++;

				proje.ProjeNo = vBolum.FakulteKisaKodu + "-" + vBolum.KisaKod + "-" + oncekiProjeID;
				int durum = projeIslemleri.Ekle(proje);

				if (durum > 0)
					return RedirectToAction(nameof(Liste));
			}
			ViewData["ProjeTipi"] = SLOlusturma.ProjeTipiListele(AnlikOturum.Kullanici.Akademisyen.FakulteID);
			ViewData["ProjeDurumu"] = SLOlusturma.ProjeDurumuListele();
			ViewData["Fakulte"] = SLOlusturma.FakulteListele();
			ViewData["Bolum"] = SLOlusturma.BolumListele();
			ViewData["Danisman"] = SLOlusturma.AkademisyenListele(AnlikOturum.Kullanici.Akademisyen.FakulteID, AnlikOturum.Kullanici.Akademisyen.BolumID);
			ViewData["Ogrenci"] = SLOlusturma.OgrenciListele(AnlikOturum.Kullanici.Akademisyen.FakulteID, AnlikOturum.Kullanici.Akademisyen.BolumID);
			return View("EkleDuzenle", proje);
		}

		public ActionResult Duzenle(int? id)
		{
			if (id == null)
				return RedirectToAction(nameof(Liste));

			Proje proje = projeIslemleri.Bul("ID = " + id);

			if (proje == null)
				return HttpNotFound();

			ViewData["ProjeTipi"] = SLOlusturma.ProjeTipiListele(AnlikOturum.Kullanici.Akademisyen.FakulteID);
			ViewData["ProjeDurumu"] = SLOlusturma.ProjeDurumuListele();
			ViewData["Fakulte"] = SLOlusturma.FakulteListele();
			ViewData["Bolum"] = SLOlusturma.BolumListele();
			ViewData["Danisman"] = SLOlusturma.AkademisyenListele(AnlikOturum.Kullanici.Akademisyen.FakulteID,AnlikOturum.Kullanici.Akademisyen.BolumID);
			ViewData["Ogrenci"] = SLOlusturma.OgrenciListele(AnlikOturum.Kullanici.Akademisyen.FakulteID, AnlikOturum.Kullanici.Akademisyen.BolumID);
			return View("EkleDuzenle", proje);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Duzenle(int id, Proje gelenProje)
		{
			if (ModelState.IsValid)
			{
				VBolum vBolum;
				Proje proje = projeIslemleri.Bul("ID = " + id);

				if (gelenProje.FakulteID != proje.FakulteID || gelenProje.BolumID != proje.BolumID)
				{
					vBolum = vbolumIslemleri.Bul("FakulteID = " + gelenProje.FakulteID + " And BolumID = " + gelenProje.BolumID);
					proje.ProjeNo = vBolum.FakulteKisaKodu + "-" + vBolum.KisaKod + "-" + proje.ID;
				}

				proje.BaslangicTarihi = gelenProje.BaslangicTarihi;
				proje.BitisTarihi = gelenProje.BitisTarihi;
				proje.BolumID = gelenProje.BolumID;
				proje.CevreselEtkileri = gelenProje.CevreselEtkileri;
				proje.DanismanID = gelenProje.DanismanID;
				proje.Durum = gelenProje.Durum;
				proje.EkAlan1 = gelenProje.EkAlan1;
				proje.EkAlan2 = gelenProje.EkAlan2;
				proje.EkDosya = gelenProje.EkDosya;
				proje.EtikSakincalari = gelenProje.EtikSakincalari;
				proje.Etkin = gelenProje.Etkin;
				proje.FakulteID = gelenProje.FakulteID;
				proje.MaliyetArastirmasi = gelenProje.MaliyetArastirmasi;
				proje.OgrenciID = gelenProje.OgrenciID;
				proje.ProjeAciklamasi = gelenProje.ProjeAciklamasi;
				proje.ProjeAdi = gelenProje.ProjeAdi;
				proje.ProjeKonusuAmaci = gelenProje.ProjeKonusuAmaci;
				proje.ProjeTipi = gelenProje.ProjeTipi;
				proje.Rapor = gelenProje.Rapor;
				proje.Tarih = DateTime.Now;
				proje.YararlanilanKaynaklar = gelenProje.YararlanilanKaynaklar;

				int durum = projeIslemleri.Guncelle("ID = " + id, proje);

				if (durum > 0)
					return RedirectToAction(nameof(Liste));
			}
			ViewData["ProjeTipi"] = SLOlusturma.ProjeTipiListele(AnlikOturum.Kullanici.Akademisyen.FakulteID);
			ViewData["ProjeDurumu"] = SLOlusturma.ProjeDurumuListele();
			ViewData["Fakulte"] = SLOlusturma.FakulteListele();
			ViewData["Bolum"] = SLOlusturma.BolumListele();
			ViewData["Danisman"] = SLOlusturma.AkademisyenListele(AnlikOturum.Kullanici.Akademisyen.FakulteID, AnlikOturum.Kullanici.Akademisyen.BolumID);
			ViewData["Ogrenci"] = SLOlusturma.OgrenciListele(AnlikOturum.Kullanici.Akademisyen.FakulteID, AnlikOturum.Kullanici.Akademisyen.BolumID);
			return View("EkleDuzenle", gelenProje);
		}

		public ActionResult Sil(int? id)
		{
			if (id == null)
				return RedirectToAction(nameof(Liste));

			Proje proje = projeIslemleri.Bul("ID = " + id + " And Silindi = 0");

			if (proje == null)
				return HttpNotFound();

			return View(proje);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Sil(int id, Proje gelenProje)
		{
			int durum = projeIslemleri.Guncelle("ID = " + id, "Silindi", true, typeof(bool));
			if (durum > 0)
				return RedirectToAction(nameof(Liste));
			return View();
		}

		#endregion

		#region ProjeOneriIslemleri

		public ActionResult OneriListesi()
		{
			List<VProjeOneri> projeOneri;
			switch (AnlikOturum.Kullanici.Yetki)
			{
				case (int)Yetkilendirme.SystemAdmin:
					projeOneri = vprojeOneriIslemleri.VeriGetir("Durum <= " + (int)ProjeOneriDurumu.Onaylandi); break;
				case (int)Yetkilendirme.BolumBaskani:
					projeOneri = vprojeOneriIslemleri.VeriGetir(
						"FakulteID = " + AnlikOturum.Kullanici.Akademisyen.FakulteID + " And BolumID = " + AnlikOturum.Kullanici.Akademisyen.BolumID + " And Durum = " + (int)ProjeOneriDurumu.DanismanOnayi
					);
					break;
				case (int)Yetkilendirme.Danisman:
					projeOneri = vprojeOneriIslemleri.VeriGetir(
						"FakulteID = " + AnlikOturum.Kullanici.Akademisyen.FakulteID + " And BolumID = " + AnlikOturum.Kullanici.Akademisyen.BolumID + " And DanismanID = " + AnlikOturum.Kullanici.Akademisyen.ID + " And Durum = " + (int)ProjeOneriDurumu.Beklemede
					);
					break;
				default: projeOneri = new List<VProjeOneri>(); break;
			}
			return View(projeOneri);
		}

		public ActionResult OneriOnayi(int? id)
		{
			if (id == null)
				return RedirectToAction(nameof(OneriListesi));

			VProjeOneri projeOneri = vprojeOneriIslemleri.Bul("ID = " + id);

			if (projeOneri == null)
				return HttpNotFound();

			return View(projeOneri);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult OneriOnayi(int id, bool onay)
		{
			if (AnlikOturum.Kullanici.Yetki <= (int)Yetkilendirme.BolumBaskani && onay)
			{
				ProjeOneri projeOneri = projeOneriIslemleri.Bul("ID = " + id);
				projeOneri.Durum = (int)ProjeOneriDurumu.Onaylandi;
				projeOneri.BolumBaskaniOnay = true;
				projeOneri.BolumBaskaniOnayTarihi = DateTime.Now;

				int durum = projeOneriIslemleri.Guncelle("ID = " + id, projeOneri);

				if (durum > 0)
				{
					Proje proje = new Proje()
					{
						BaslangicTarihi = DateTime.Now,
						ProjeAdi = projeOneri.ProjeAdi,
						Etkin = true,

SUTFProjeYonetimi/Views/Proje/Detay.cshtml
@model SUTFProjeYonetimi.Models.Proje
@{
	ViewBag.Title = "Proje Detayları";
}

<div id="ribbon">
	<ol class="breadcrumb">
		<li>Proje</li>
		<li>Proje Detayları</li>
	</ol>
</div>
<div id="content">
	<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="margin-bottom:25px">
		<div class="jarviswidget jarviswidget-color-darken" id="wid-id-1" data-widget-editbutton="false" data-widget-custombutton="false">
			<header>
				<span class="widget-icon"> <i class="fa fa-file"></i> </span>
				<h2>Proje Detay Formu</h2>
			</header>
			<div>
				<div class="jarviswidget-editbox"></div>
				<div class="widget-body container-fluid">
					<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
						<h4>Proje Detayları</h4>
						<hr />
						<div class="table-responsive">
							<table class="table  table-striped table-bordered">
								<tbody>
									<tr>
										<td><b>Proje No.</b></td>
										<td>@Model.ProjeNo</td>
									</tr>
									<tr>
										<td><b>Proje Adı</b></td>
										<td>@Model.ProjeAdi</td>
									</tr>
									<tr>
										<td><b>Proje Açıklaması</b></td>
										<td>@Model.ProjeAciklamasi</td>
									</tr>
									<tr>
										<td><b>Başlangıç Tarihi</b></td>
										<td>@Model.BaslangicTarihi.ToString("dd/MM/yyyy")</td>
									</tr>
									<tr>
										<td><b>Bitiş Tarihi</b></td>
										<td>@Model.BitisTarihi.ToString("dd/MM/yyyy")</td>
									</tr>
									<tr>
										<td><b>Etkin</b></td>
										<td>@(Model.Etkin ? "Etkin" : "Etkin Değil")</td>
									</tr>
								</tbody>
							</table>
						</div>

						<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
							<hr />
							@Html.ActionLink("Listeye Dön", "Liste", null, new { @class = "btn btn-primary btn-block" })
						</div>
					</div>
				</div>
			</div>
		</div>
	</article>
</div>

SUTFProjeYonetimi/Views/Proje/Liste.cshtml
@model List<SUTFProjeYonetimi.Models.ViewModel.VProje>
@{
	ViewBag.Title = "Proje Listesi";
}

<div id="ribbon">
	<ol class="breadcrumb">
		<li>Proje</li>
		<li>Proje Listesi</li>
	</ol>
</div>
<div id="content">
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="margin-bottom:25px">
		<div class="jarviswidget jarviswidget-color-blueLight" id="wid-id-0" data-widget-editbutton="false">
			<header>
				<span class="widget-icon"> <i class="fa fa-table"></i> </span>
				<h2>Projeler</h2> <h2> <a href="~/Proje/Ekle" class="btn bg-color-greenDark txt-color-white">Proje Ekle </a></h2>
			</header>
			<div>
				<div class="jarviswidget-editbox"></div>
				<div class="widget-body no-padding">
					<table id="dt_basic" class="table table-striped table-bordered table-hover" width="100%">
						<thead>
							<tr>
								<th data-class="expand"> Öğrenci No.</th>
								<th> Öğrenci</th>
								<th> Proje Adı</th>
								<th> Başlangıç Tarihi</th>
								<th data-hide="phone">Etkin/Etkin Değil</th>
								<th>İşlemler</th>
							</tr>
						</thead>
						<tbody>
							@foreach (var items in Model)
							{
								if (items.Etkin)
								{
									<tr>
										<td>@items.OgrenciNo</td>
										<td>@(items.OgrenciAd + " " + items.OgrenciSoyad)</td>
										<td>@items.ProjeAdi</td>
										<td>@items.BaslangicTarihi.ToString("dd/MM/yyyy")</td>
										<td>Etkin</td>
										<td>
											<a href="~/Proje/Duzenle/@items.ID" class="btn btn-warning hidden-sm hidden-xs"><i class="fa fa-pencil"></i></a>
											<a href="~/Proje/Sil/@items.ID" class="btn btn-danger hidden-sm hidden-xs"><i class="fa fa-times"></i></a>
											<a href="~/Proje/Duzenle/@items.ID" class="btn btn-xs btn-warning hidden-md hidden-lg"><i class="fa fa-pencil"></i></a>
											<a href="~/Proje/Sil/@items.ID" class="btn btn-xs btn-danger hidden-md hidden-lg"><i class="fa fa-times"></i></a>
										</td>
									</tr>
								}
								else
								{
									<tr class="danger">
										<td>@items.OgrenciNo</td>
										<td>@(items.OgrenciAd + " " + items.OgrenciSoyad)</td>
										<td>@items.ProjeAdi</td>
										<td>@items.BaslangicTarihi.ToString("dd/MM/yyyy")</td>
										<td>Etkin Değil</td>
										<td>
											<a href="~/Proje/Duzenle/@items.ID" class="btn btn-warning hidden-sm hidden-xs"><i class="fa fa-pencil"></i></a>
											<a href="~/Proje/Sil/@items.ID" class="btn btn-danger hidden-sm hidden-xs"><i class="fa fa-times"></i></a>
											<a href="~/Proje/Duzenle/@items.ID" class="btn btn-xs btn-warning hidden-md hidden-lg"><i class="fa fa-pencil"></i></a>
											<a href="~/Proje/Sil/@items.ID" class="btn btn-xs btn-danger hidden-md hidden-lg"><i class="fa fa-times"></i></a>
										</td>
									</tr>
								}
							}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@section scripts
{
	<script src="~/Assets/js/plugin/datatables/jquery.dataTables.min.js"></script>
	<script src="~/Assets/js/plugin/datatables/dataTables.colVis.min.js"></script>
	<script src="~/Assets/js/plugin/datatables/dataTables.tableTools.min.js"></script>
	<script src="~/Assets/js/plugin/datatables/dataTables.bootstrap.min.js"></script>
	<script src="~/Assets/js/plugin/datatable-responsive/datatables.responsive.min.js"></script>
	<script>
		$(document).ready(function () {
			pageSetUp();
			var responsiveHelper_dt_basic = undefined;
			var breakpointDefinition = {
				tablet: 1024,
				phone: 480
			};
			$('#dt_basic').dataTable({
				"sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-12 hidden-xs'l>r>" +
					"t" +
					"<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-xs-12 col-sm-6'p>>",
				"autoWidth": true,
				"oLanguage": {
					"sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>'
				},
				"preDrawCallback": function () {
					if (!responsiveHelper_dt_basic) {
						responsiveHelper_dt_basic = new ResponsiveDatatablesHelper($('#dt_basic'), breakpointDefinition);
					}
				},
				"rowCallback": function (nRow) {
					responsiveHelper_dt_basic.createExpandIcon(nRow);
				},
				"drawCallback": function (oSettings) {
					responsiveHelper_dt_basic.respond();
				}
			});
		})
	</script>
}

SUTFProjeYonetimi/Views/Proje/OneriOnayi.cshtml
@model SUTFProjeYonetimi.Models.ViewModel.VProjeOneri
@{
	ViewBag.Title = "Proje Öneri Onayı";
}

<div id="ribbon">
	<ol class="breadcrumb">
		<li>Proje</li>
		<li>Proje Öneri Onayı</li>
	</ol>
</div>
<div id="content">
	<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="margin-bottom:25px">
		<div class="jarviswidget jarviswidget-color-darken" id="wid-id-1" data-widget-editbutton="false" data-widget-custombutton="false">
			<header>
				<span class="widget-icon"> <i class="fa fa-file"></i> </span>
				<h2>Proje Öneri Formu</h2>
			</header>
			<div>
				<div class="jarviswidget-editbox"></div>
				<div class="widget-body container-fluid">
					<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
						<h4>Öğrenci Detayları</h4>
						<hr />
						<div class="table-responsive">
							<table class="table  table-striped table-bordered">
								<tbody>
									<tr>
										<td><b>Öğrenci Numarası</b></td>
										<td>@Model.OgrenciNo</td>
									</tr>
									<tr>
										<td><b>Öğrenci Adı Soyadı</b></td>
										<td>@(Model.OgrenciAd + " " + Model.OgrenciSoyad)</td>
									</tr>
									<tr>
										<td><b>Danışman Adı Soyadı</b></td>
										<td>@(Model.DanismanAd + " " + Model.DanismanSoyad)</td>
									</tr>
								</tbody>
							</table>
						</div>
						<h4>Proje Öneri Detayları</h4>
						<hr />
						<div class="table-responsive">
							<table class="table  table-striped table-bordered">
								<tbody>
									<tr>
										<td><b>Proje Adı</b></td>
										<td>@Model.ProjeAdi</td>
									</tr>
									<tr>
										<td><b>Proje Konusu ve Amacı</b></td>
										<td>@Model.ProjeKonusuAmaci</td>
									</tr>
									<tr>
										<td><b>Maliyet Araştırması</b></td>
										<td>@Model.MaliyetArastirmasi</td>
									</tr>
									<tr>
										<td><b>Çevresel Etkileri</b></td>
										<td>@Model.CevreselEtkileri</td>
									</tr>
									<tr>
										<td><b>Etik Sakıncaları</b></td>
										<td>@Model.EtikSakincalari</td>
									</tr>
									<tr>
										<td><b>Yararlanılan Kaynaklar</b></td>
										<td>@Model.YararlanilanKaynaklar</td>
									</tr>
								</tbody>
							</table>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<hr />
							<div class="col-lg-4 col-lg-offset-1 col-md-4 col-md-offset-1 col-sm-4 col-sm-offset-1 col-xs-10 col-xs-offset-1">
								@using (Html.BeginForm("OneriOnayi", "Proje", FormMethod.Post))
								{
									@Html.AntiForgeryToken()
									@Html.Hidden("onay", true)
									<button type="submit" class="btn btn-success btn-block">Onayla</button>
								}
							</div>
							<div class="col-lg-4 col-lg-offset-1 col-md-4 col-md-offset-1 col-sm-4 col-sm-offset-1 col-xs-10 col-xs-offset-1">
								@using (Html.BeginForm("OneriRed", "Proje", new { Model.ID }, FormMethod.Post))
								{
									@Html.AntiForgeryToken()
									@Html.Hidden("onay", false)
									<button type="submit" class="btn btn-danger btn-block">Reddet</button>
								}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</article>
</div>

SUTFProjeYonetimi/Views/Proje/ProjeTipiSil.cshtml
@model SUTFProjeYonetimi.Models.ProjeTipi
@{
	ViewBag.Title = "Proje Tipi Sil";
}

<div id="ribbon">
	<ol class="breadcrumb">
		<li>Proje Tipi</li>
		<li>Proje Tipi Sil</li>
	</ol>
</div>
<div id="content">
	<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="margin-bottom:25px">
		<div class="jarviswidget jarviswidget-color-darken" id="wid-id-1" data-widget-editbutton="false" data-widget-custombutton="false">
			<header>
				<span class="widget-icon"> <i class="fa fa-file"></i> </span>
				<h2>Proje Tipi Detay Formu</h2>
			</header>
			<div>
				<div class="jarviswidget-editbox"></div>
				<div class="widget-body container-fluid">
					<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
						<h4>Öğrenci Detayları</h4>
						<hr />
						<div class="table-responsive">
							<table class="table  table-striped table-bordered">
								<tbody>
									<tr>
										<td><b>Proje Tipi Adı</b></td>
										<td>@Model.Ad</td>
									</tr>
									<tr>
										<td><b>Etkin</b></td>
										<td>@(Model.Etkin ? "Etkin" : "Etkin Değil")</td>
									</tr>
								</tbody>
							</table>
						</div>

						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<hr />
							<div class="col-lg-4 col-lg-offset-1 col-md-4 col-md-offset-1 col-sm-4 col-sm-offset-1 col-xs-10 col-xs-offset-1">
								@using (Html.BeginForm())
								{
									@Html.AntiForgeryToken()
									<button type="submit" class="btn btn-danger btn-block">Sil</button>
								}
							</div>
							<div class="col-lg-4 col-lg-offset-1 col-md-4 col-md-offset-1 col-sm-4 col-sm-offset-1 col-xs-10 col-xs-offset-1">
								@Html.ActionLink("Listeye Dön", "ProjeTipleri", null, new { @class = "btn btn-primary btn-block" })
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</article>
</div>