SUTFProjeYonetimi/Models/Ogrenci.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SUTFProjeYonetimi.Models
{
	public class Ogrenci
	{
		[Key]
		public int ID { get; set; }

		[MaxLength(15), DisplayName("Öğrenci No.")]
		public string OgrenciNo { get; set; }

		[DisplayName("Fakülte")]
		public int FakulteID { get; set; }

		[DisplayName("Bölüm")]
		public int BolumID { get; set; }

		[Required, MaxLength(11), DisplayName("T.C. Kimlik No.")]
		public string TCKNO { get; set; }

		[Required, MaxLength(50)]
		public string Ad { get; set; }

		[Required, MaxLength(50)]
		public string Soyad { get; set; }

		[DisplayName("Sınıf")]
		public int Sinif { get; set; }

		[DisplayName("Öğrenim Tipi (NÖ-İÖ)")]
		public int OgrenimTipi { get; set; }

		[DisplayName("Şifre")]
		public string Sifre { get; set; }

		public bool Etkin { get; set; }

		public bool Silindi { get; set; }
	}
}

SUTFProjeYonetimi/Models/Proje.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SUTFProjeYonetimi.Models
{
	public class Proje
	{
		[Key, DisplayName("Proje No.")]
		public int ID { get; set; }

		[DisplayName("Fakülte")]
		public int FakulteID { get; set; }

		[DisplayName("Bölüm")]
		public int BolumID { get; set; }

		[DisplayName("Dönemi")]
		public int DonemID { get; set; }

		[DisplayName("Öğrenci")]
		public int OgrenciID { get; set; }

		[DisplayName("Danışman")]
		public int DanismanID { get; set; }

		public string ProjeNo { get; set; }

		public int ProjeTipi { get; set; }

		[Required, MaxLength(255), DisplayName("Proje Adı")]
		public string ProjeAdi { get; set; }

		[Required, MaxLength(255), DisplayName("Proje Açıklaması")]
		public string ProjeAciklamasi { get; set; }

		[DisplayName("Proje Konusu ve Amacı")]
		public string ProjeKonusuAmaci { get; set; }

		[DisplayName("Maliyet Araştırması")]
		public string MaliyetArastirmasi { get; set; }

		[DisplayName("Çevresel Etkileri")]
		public string CevreselEtkileri { get; set; }

		[DisplayName("Etik Sakıncaları")]
		public string EtikSakincalari { get; set; }

		[DisplayName("Yaralanılan Kaynaklar")]
		public string YararlanilanKaynaklar { get; set; }

		public DateTime Tarih { get; set; }

		public int Durum { get; set; }

		[DisplayName("Ek Dosya")]
		public string EkDosya { get; set; }

		[DisplayName("Başlangıç Tarihi")]
		public DateTime BaslangicTarihi { get; set; }

		[DisplayName("Bitiş Tarihi")]
		public DateTime BitisTarihi { get; set; }

		public string Rapor { get; set; }

		[MaxLength(255), DisplayName("Ek Alan-1")]
		public string EkAlan1 { get; set; }

		[MaxLength(255), DisplayName("Ek Alan-2")]
		public string EkAlan2 { get; set; }

		public bool Etkin { get; set; }

		public bool Silindi { get; set; }
	}
}

SUTFProjeYonetimi/Controllers/OgrenciController.cs
using SUTFProjeYonetimi.Filters;
using SUTFProjeYonetimi.Models;
using SUTFProjeYonetimi.Models.EkModel;
using SUTFProjeYonetimi.Models.Enum;
using SUTFProjeYonetimi.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;
using static SUTFProjeYonetimi.App_Start.Tanimlamalar;

namespace SUTFProjeYonetimi.Controllers
{
	[AnlikOturumFilter]
	[HataFilter]
	public class OgrenciController : Controller
	{
		#region CRUD Islemleri

		/*
		 *	CRUD İşlemlerini yalnızca Akademisyen gerçekleştirebilir. Öğrenciler bu işlemleri gerçekleştiremezler.
		 * 
		 *	Yetkilendirmeler
		 *	-------------------
		 *	1 - Dekan -> Bütün Öğrencileri Görebilir
		 *	2 - Bölüm Başkanı -> Sadece Kendi Bölümünün Öğrencilerini Görebilir
		 *	3 - Danışman -> Sadece Kendi Danışmanlık Yaptığı Öğrencileri Görebilir
		 * 
		 */

		[DanismanFilter]
		public ActionResult Liste()
		{
			List<VOgrenci> ogrenciler;
			switch (AnlikOturum.Kullanici.Yetki)
			{
				case (int)Yetkilendirme.SystemAdmin:
					ogrenciler = vogrenciIslemleri.VeriGetir(); break;
				case (int)Yetkilendirme.Dekan:
					ogrenciler = vogrenciIslemleri.VeriGetir("FakulteID = " + AnlikOturum.Kullanici.Akademisyen.FakulteID + " And Silindi = 0"); break;
				case (int)Yetkilendirme.BolumBaskani:
					ogrenciler = vogrenciIslemleri.VeriGetir("Silindi = 0 AND FakulteID = " + AnlikOturum.Kullanici.Akademisyen.FakulteID + " AND BolumID = " + AnlikOturum.Kullanici.Akademisyen.BolumID); break;
				case (int)Yetkilendirme.Danisman:
					ogrenciler = vogrenciIslemleri.VeriGetir("Silindi = 0 AND DanismanID = " + AnlikOturum.Kullanici.Akademisyen.ID); break;
				case (int)Yetkilendirme.Ogrenci:
					return RedirectToAction("Anasayfa", "Panel");
				default: return HttpNotFound();
			}
			return View(ogrenciler);
		}

		[DanismanFilter]
		public ActionResult Detay(int? id)
		{
			if (id == null)
				return RedirectToAction(nameof(Liste));

			VOgrenci ogrenci;
			switch (AnlikOturum.Kullanici.Yetki)
			{
				case (int)Yetkilendirme.SystemAdmin:
					ogrenci = vogrenciIslemleri.Bul("ID = " + id); break;
				case (int)Yetkilendirme.Dekan:
					ogrenci = vogrenciIslemleri.Bul("FakulteID = " + AnlikOturum.Kullanici.Akademisyen.FakulteID + " And ID = " + id + " AND Silindi = 0");
					break;
				case (int)Yetkilendirme.BolumBaskani:
					ogrenci = vogrenciIslemleri.Bul("FakulteID = " + AnlikOturum.Kullanici.Akademisyen.FakulteID + " And BolumID = " + AnlikOturum.Kullanici.Akademisyen.BolumID + " And ID = " + id + " AND Silindi = 0");
					break;
				case (int)Yetkilendirme.Danisman:
					ogrenci = vogrenciIslemleri.Bul("ID = " + id + " AND Silindi = 0 AND DanismanID = " + AnlikOturum.Kullanici.Akademisyen.ID);
					break;
				case (int)Yetkilendirme.Ogrenci:
					return RedirectToAction("Anasayfa", "Panel");
				default: return HttpNotFound();
			}

			if (ogrenci == null)
				return HttpNotFound();

			return View(ogrenci);
		}

		[DanismanFilter]
		public ActionResult Ekle()
		{
			ViewData["Fakulte"] = SLOlusturma.FakulteListele();
			ViewData["Bolum"] = SLOlusturma.BolumListele();
			ViewData["Sinif"] = SLOlusturma.SinifListele();
			ViewData["OgrenimTipi"] = SLOlusturma.OgrenimTipiListele();
			return View("EkleDuzenle");
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[DanismanFilter]
		public ActionResult Ekle(Ogrenci ogrenci)
		{
			if (ModelState.IsValid)
			{
				ogrenci.Silindi = false;
				int durum = ogrenciIslemleri.Ekle(ogrenci);

				if (durum > 0)
					return RedirectToAction(nameof(Liste));
			}
			ViewData["Fakulte"] = SLOlusturma.FakulteListele();
			ViewData["Bolum"] = SLOlusturma.BolumListele();
			ViewData["Sinif"] = SLOlusturma.SinifListele();
			ViewData["OgrenimTipi"] = SLOlusturma.OgrenimTipiListele();

			return View("EkleDuzenle", ogrenci);
		}

		[DanismanFilter]
		public ActionResult Duzenle(int? id)
		{
			if (id == null)
				return RedirectToAction(nameof(Liste));

			VOgrenci ogrenci;
			switch (AnlikOturum.Kullanici.Yetki)
			{
				case (int)Yetkilendirme.SystemAdmin:
				case (int)Yetkilendirme.Dekan:
					ogrenci = vogrenciIslemleri.Bul("ID = " + id); break;
				case (int)Yetkilendirme.BolumBaskani:
					ogrenci = vogrenciIslemleri.Bul("ID = " + id + " AND FakulteID = " + AnlikOturum.Kullanici.Akademisyen.FakulteID + " AND BolumID = " + AnlikOturum.Kullanici.Akademisyen.BolumID);
					break;
				case (int)Yetkilendirme.Danisman:
					ogrenci = vogrenciIslemleri.Bul("ID = " + id + " AND Silindi = 0 AND DanismanID = " + AnlikOturum.Kullanici.Akademisyen.ID);
					break;
				default: return HttpNotFound();
			}

			if (ogrenci == null)
				return HttpNotFound();

			ViewData["Fakulte"] = SLOlusturma.FakulteListele();
			ViewData["Bolum"] = SLOlusturma.BolumListele();
			ViewData["Sinif"] = SLOlusturma.SinifListele();
			ViewData["OgrenimTipi"] = SLOlusturma.OgrenimTipiListele();

			return View("EkleDuzenle", ogrenci);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[DanismanFilter]
		public ActionResult Duzenle(int id, VOgrenci gelenOgrenci)
		{
			if (ModelState.IsValid)
			{
				Ogrenci ogrenci = ogrenciIslemleri.Bul("ID = " + id);
				ogrenci.Ad = gelenOgrenci.Ad;
				ogrenci.BolumID = gelenOgrenci.BolumID;
				ogrenci.FakulteID = gelenOgrenci.FakulteID;
				ogrenci.OgrenciNo = gelenOgrenci.OgrenciNo;
				ogrenci.OgrenimTipi = gelenOgrenci.OgrenimTipi;
				ogrenci.Sinif = gelenOgrenci.Sinif;
				ogrenci.Soyad = gelenOgrenci.Soyad;
				ogrenci.TCKNO = gelenOgrenci.TCKNO;
				ogrenci.Sifre = gelenOgrenci.Sifre;
				ogrenci.Etkin = gelenOgrenci.Etkin;

				int durum = ogrenciIslemleri.Guncelle("ID = " + id, ogrenci);
				if (durum > 0)
					return RedirectToAction(nameof(Liste));
			}
			ViewData["Fakulte"] = SLOlusturma.FakulteListele();
			ViewData["Bolum"] = SLOlusturma.BolumListele();
			ViewData["Sinif"] = SLOlusturma.SinifListele();
			ViewData["OgrenimTipi"] = SLOlusturma.OgrenimTipiListele();
			return View("EkleDuzenle", gelenOgrenci);
		}

		public ActionResult Sil(int? id)
		{
			if (id == null)
				return RedirectToAction(nameof(Liste));

			VOgrenci ogrenci;
			switch (AnlikOturum.Kullanici.Yetki)
			{
				case (int)Yetkilendirme.SystemAdmin:
				case (int)Yetkilendirme.Dekan:
					ogrenci = vogrenciIslemleri.Bul("ID = " + id + " And Silindi = 0"); break;
				case (int)Yetkilendirme.BolumBaskani:
					ogrenci = vogrenciIslemleri.Bul("ID = " + id + " AND FakulteID = " + AnlikOturum.Kullanici.Akademisyen.FakulteID + " AND BolumID = " + AnlikOturum.Kullanici.Akademisyen.BolumID + " And Silindi = 0"); break;
				case (int)Yetkilendirme.Danisman:
					ogrenci = vogrenciIslemleri.Bul("ID = " + id + "  AND DanismanID = " + AnlikOturum.Kullanici.Akademisyen.ID + " And Silindi = 0");
					break;
				default: return HttpNotFound();
			}

			if (ogrenci == null)
				return HttpNotFound();

			return View(ogrenci);
		}

		// Silme işlemi asla gerçekleşmiyor. Yalnızca öğrenci silinmiş gibi gösterilerek işlem yapılıyor.

		[HttpPost]
		[ValidateAntiForgeryToken]
		[DanismanFilter]
		public ActionResult Sil(int id, Ogrenci gelenOgrenci)
		{
			Ogrenci ogrenci = ogrenciIslemleri.Bul("ID = " + id);
			int durum = ogrenciIslemleri.Guncelle("ID = " + id, "Silindi", true, typeof(bool));

			if (durum > 0)
				return RedirectToAction(nameof(Liste));

			return View(gelenOgrenci);
		}

		#endregion


		#region OgrenciHareketleri

		/*
		 * 
		 *	Bu işlemler yalnızca öğrenci tarafından gerçekleştirilir. Diğer yetkiye sahip kişiler sadece proje
		 *	controller içerisinde yer alan metotlar ile onaylama ve reddetme işlemi gerçekleştirebilir.
		 *	
		 */

		[OgrenciFilter]
		public ActionResult Proje()
		{
			List<VProje> projeler = vprojeIslemleri.VeriGetir("OgrenciID = " + AnlikOturum.Kullanici.Ogrenci.ID);
			//List<VProjeOneri> projeOnerileri = vprojeOneriIslemleri.VeriGetir("OgrenciID = " + AnlikOturum.Kullanici.NitelikID);

			//ViewData["ProjeOnerileri"] = projeOnerileri;

			return View(projeler);
		}
		
		[OgrenciFilter]
		public ActionResult DanismanDegisiklikTalebi()
		{
			ViewData["Danismanlar"] = SLOlusturma.AkademisyenListele(AnlikOturum.Kullanici.Ogrenci.FakulteID, AnlikOturum.Kullanici.Ogrenci.BolumID);
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken] 
		[OgrenciFilter]
		public ActionResult DanismanDegisiklikTalebi(int danisman)
		{
			if (danisman <= 0)
				return RedirectToAction("Anasayfa", "Panel");
			else
			{
				// TODO : Uygun Model Hazırlanacak
			}
			ViewData["Danismanlar"] = SLOlusturma.AkademisyenListele(AnlikOturum.Kullanici.Ogrenci.FakulteID, AnlikOturum.Kullanici.Ogrenci.BolumID);
			return View(danisman);
		}

		public ActionResult RaporTeslim(int? id)
		{
			if (id == null)
				return RedirectToAction("Anasayfa", "Panel");

			Proje proje = projeIslemleri.Bul("ID = " + id + " And Silindi = 0");

			if (proje == null)
				return HttpNotFound();

			return View(proje);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[OgrenciFilter]
		public ActionResult RaporTeslim(int id, HttpPostedFileBase rapor)
		{
			if (ModelState.IsValid)
			{
				try
				{
					if (rapor.ContentLength > 0)
					{
						string _FileName = Path.GetFileName(rapor.FileName);
						string _path = Path.Combine(Server.MapPath("~/Raporlar"), _FileName);

						Proje proje = projeIslemleri.Bul("ID = " + id);
						proje.Rapor = _path;
						int durum = projeIslemleri.Guncelle("ID = " + id, "Rapor", _path, typeof(string));

						if(durum > 0)
							rapor.SaveAs(_path);
					}
					ViewBag.Message = "Dosya Yükleme İşlemi Başarılı!";
					return View();
				}
				catch
				{
					ViewBag.Hata = "Dosya Yükleme İşlemi Başarısız!";
					return View();
				}
			}
			return View();
		}

		#endregion

		#region ProjeOneriIslemleri

		/*
		 *	Bu işlemleri sadece öğrenciler gerçekleştirebilir. Anasayfada yer alan kısımda bu işlemlere erişebilir.
		 */

		[OgrenciFilter]
		public ActionResult ProjeOnerisiDetay(int? id)
		{
			if (id == null)
				return RedirectToAction("Anasayfa", "Panel");

SUTFProjeYonetimi/Views/Ogrenci/DanismanDegisiklikTalebi.cshtml
@{
	ViewBag.Title = "Danışman Değişiklik Talebi";

	var danismanlar = ViewData["Danismanlar"] as SelectList;
}

<div id="ribbon">
	<ol class="breadcrumb">
		<li>Öğrenci</li>
		<li>Danışman Değişiklik Talebi</li>
	</ol>
</div>
<div id="content">
	<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="margin-bottom:25px">
		<div class="jarviswidget jarviswidget-color-darken" id="wid-id-1" data-widget-editbutton="false" data-widget-custombutton="false">
			<header>
				<span class="widget-icon"> <i class="fa fa-file"></i> </span>
				<h2>Danışman Değişiklik Talep Formu</h2>
			</header>
			<div>
				<div class="jarviswidget-editbox"></div>
				<div class="widget-body container-fluid">
					@using (Html.BeginForm("ProjeOneriOnayi", "Proje", FormMethod.Post))
					{
						<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
							<div class="">
								<select id="danisman" class="form-control">
									@foreach (var item in danismanlar)
									{
										<option value="@item.Value">@item.Text</option>
									}
								</select>
							</div>
							<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
								<hr />
								<div class="col-lg-4 col-lg-offset-1 col-md-4 col-md-offset-1 col-sm-4 col-sm-offset-1 col-xs-10 col-xs-offset-1">

									<button type="submit" class="btn btn-success btn-block">Onayla</button>

								</div>
							</div>
						</div>
					}
				</div>
			</div>
		</div>
	</article>
</div>

SUTFProjeYonetimi/Views/Ogrenci/Detay.cshtml
@model SUTFProjeYonetimi.Models.Ogrenci
@{
	ViewBag.Title = "Öğrenci Detayları";
}

<div id="ribbon">
	<ol class="breadcrumb">
		<li>Öğrenci</li>
		<li>Öğrenci Detayları</li>
	</ol>
</div>
<div id="content">
	<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="margin-bottom:25px">
		<div class="jarviswidget jarviswidget-color-darken" id="wid-id-1" data-widget-editbutton="false" data-widget-custombutton="false">
			<header>
				<span class="widget-icon"> <i class="fa fa-file"></i> </span>
				<h2>Öğrenci Detay Formu</h2>
			</header>
			<div>
				<div class="jarviswidget-editbox"></div>
				<div class="widget-body container-fluid">
					<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
						<h4>Öğrenci Detayları</h4>
						<hr />
						<div class="table-responsive">
							<table class="table  table-striped table-bordered">
								<tbody>
									<tr>
										<td><b>Öğrenci No.</b></td>
										<td>@Model.OgrenciNo</td>
									</tr>
									<tr>
										<td><b>T.C. Kimlik No.</b></td>
										<td>@Model.TCKNO</td>
									</tr>
									<tr>
										<td><b>Fakülte</b></td>
										<td>@Model.FakulteID</td>
									</tr>
									<tr>
										<td><b>Bölum</b></td>
										<td>@Model.BolumID</td>
									</tr>
									<tr>
										<td><b>Ad Soyad</b></td>
										<td>@(Model.Ad + " " + Model.Soyad)</td>
									</tr>
									<tr>
										<td><b>Sınıfı</b></td>
										<td>@Model.Sinif</td>
									</tr>
									<tr>
										<td><b>Öğrenim Tipi</b></td>
										<td>@Model.OgrenimTipi</td>
									</tr>
									<tr>
										<td><b>Etkin</b></td>
										<td>@(Model.Etkin ? "Etkin" : "Etkin Değil")</td>
									</tr>
								</tbody>
							</table>
						</div>

						<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
							<hr />
							@Html.ActionLink("Listeye Dön", "Liste", null, new { @class = "btn btn-primary btn-block" })
						</div>
					</div>
				</div>
			</div>
		</div>
	</article>
</div>

SUTFProjeYonetimi/Views/Ogrenci/ProjeOnerisiDetay.cshtml
@model SUTFProjeYonetimi.Models.ProjeOneri
@{
	ViewBag.Title = "Proje Önerisi Detay";
}

<div id="ribbon">
	<ol class="breadcrumb">
		<li>Öğrenci</li>
		<li>Proje Öneri Detayları</li>
	</ol>
</div>
<div id="content">
	<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="margin-bottom:25px">
		<div class="jarviswidget jarviswidget-color-darken" id="wid-id-1" data-widget-editbutton="false" data-widget-custombutton="false">
			<header>
				<span class="widget-icon"> <i class="fa fa-file"></i> </span>
				<h2>Proje Öneri Detay Formu</h2>
			</header>
			<div>
				<div class="jarviswidget-editbox"></div>
				<div class="widget-body container-fluid">
					<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
						<h4>Proje Öneri Detayları</h4>
						<hr />
						<div class="table-responsive">
							<table class="table  table-striped table-bordered">
								<tbody>
									<tr>
										<td><b>Proje Adı</b></td>
										<td>@Model.ProjeAdi</td>
									</tr>
									<tr>
										<td><b>Proje Konusu ve Amacı</b></td>
										<td>@Model.ProjeKonusuAmaci</td>
									</tr>
									<tr>
										<td><b>Maliyet Araştırması</b></td>
										<td>@Model.MaliyetArastirmasi</td>
									</tr>
									<tr>
										<td><b>Çevresel Etkileri</b></td>
										<td>@Model.CevreselEtkileri</td>
									</tr>
									<tr>
										<td><b>Etik Sakıncaları</b></td>
										<td>@Model.EtikSakincalari</td>
									</tr>
									<tr>
										<td><b>Yararlanılan Kaynaklar</b></td>
										<td>@Model.YararlanilanKaynaklar</td>
									</tr>
								</tbody>
							</table>
						</div>

						<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
							<hr />
							@Html.ActionLink("Anasayfaya Dön", "Anasayfa", "Panel", null, new { @class = "btn btn-primary btn-block" })
						</div>
					</div>
				</div>
			</div>
		</div>
	</article>
</div>

SUTFProjeYonetimi/Views/Ogrenci/RaporTeslim.cshtml
@model SUTFProjeYonetimi.Models.Proje
@{
	ViewBag.Title = "Rapor Teslim";
}

<div id="ribbon">
	<ol class="breadcrumb">
		<li>Öğrenci</li>
		<li>Proje Raporu Teslimi</li>
	</ol>
</div>
<div id="content">
	<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="margin-bottom:25px">
		<div class="jarviswidget jarviswidget-color-darken" id="wid-id-1" data-widget-editbutton="false" data-widget-custombutton="false">
			<header>
				<span class="widget-icon"> <i class="fa fa-file"></i> </span>
				<h2>Proje Detay Formu</h2>
			</header>
			<div>
				<div class="jarviswidget-editbox"></div>
				<div class="widget-body container-fluid">
					<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
						<h4>Proje Detayları</h4>
						<hr />
						<div class="table-responsive">
							<table class="table  table-striped table-bordered">
								<tbody>
									<tr>
										<td><b>Proje No.</b></td>
										<td>@Model.ProjeNo</td>
									</tr>
									<tr>
										<td><b>Danışman</b></td>
										<td></td>
									</tr>
									<tr>
										<td><b>Proje Adı</b></td>
										<td>@Model.ProjeAdi</td>
									</tr>
									<tr>
										<td><b>Proje Açıklaması</b></td>
										<td>@Model.ProjeAciklamasi</td>
									</tr>
									<tr>
										<td><b>Başlangıç Tarihi</b></td>
										<td>@Model.BaslangicTarihi.ToString("dd/MM/yyyy")</td>
									</tr>
								</tbody>
							</table>
						</div>

						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							@using (Html.BeginForm("Rapor Teslim", "Ogrenci", FormMethod.Post, new { enctype = "multipart/form-data" }))
							{
								<div class="form-group">
									<div class="row">
										@Html.Label("Rapor Dosyası", htmlAttributes: new { @class = "control-label col-lg-4 col-md-4 col-sm-4 col-xs-4" })
										<div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
											@Html.TextBox("rapor", "", new { type = "file" })
										</div>
									</div>
								</div>
								@*<div class="form-group">
									<div class="row">
										@Html.Label("Ek Dosya", htmlAttributes: new { @class = "control-label col-lg-4 col-md-4 col-sm-4 col-xs-4" })
										<div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
											@Html.TextBox("ekdosya", "", new { type = "file" })
										</div>
									</div>
								</div>*@
								<div class="form-group">
									<div class="col-md-offset-2 col-md-10">
										<p><button type="submit" class="btn btn-success"><i class="fa fa-save"></i>  Onayla</button> | @Html.ActionLink("Anasayfaya Dön", "Anasayfa", "Panel", null, new { @class = "btn btn-primary" })</p>
									</div>
								</div>
							}
						</div>
					</div>
				</div>
			</div>
		</div>
	</article>
</div>